### ISSUE TITLE
No update method

### ISSUE THREAD

**Issue by dterg** [bcicen/slack-progress#3]
The readme states that to update the progress bar manually, the "update" method can be called, but the progress bar class does not have this method. Substituting the `pos(self, var)` method with an update method works.

From this: 
```
@pos.setter
def pos(self, val):
    if val != self._pos:
        self._sp._update(self.channel_id, self.msg_ts, val)
        self._pos = val
```

to this:
```
def update(self, val):
    if val != self._pos:
        self._sp._update(self.channel_id, self.msg_ts, val)
        self._pos = val
```

**Comment by bcicen** [comment]
since `pos` is a property setter, it should be `ProgressBar.pos = 100`

README updated; thanks for catching this!
